language: java
jdk: oraclejdk8

script:
  - ./gradlew clean build -Pversion_name=0.3.0.$TRAVIS_BUILD_NUMBER

after_success:
  - ./gradlew bintrayUpload publishPlugins -Pversion_name=0.3.0.$TRAVIS_BUILD_NUMBER -Pbintray_user=$BINTRAY_USER -Pbintray_api_key=$BINTRAY_API_KEY  -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET